name = "apollo"
type = "webpack"
account_id = "0f3abffd1fce3d4a334797303f23b609"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv-namespaces = [
	{ binding = "secrets", id = "48d7acabba644dd0aa149a233c22bde7" },
	{ binding = "tokens", id = "8db4037f893d416caf06c9fe8741c943" },
]
